# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3fca57f01828323cee680348b8399ec60ea0ed61d5ab53b7bf75aa161297857ad77495aa6d4be9f973174033d1865fe453563a574868baf7c06773eeacf95b2a

test:
  secret_key_base: 5b01450194e93755760f45d83c01306bd2312fc75e3799afd92de7e7f94fd372e5f81374607a900a054b349baa6cbcc640ce6f1b7b9116091591e44af48489d7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
